--[[
    🌟 BABFT HACK - СУПЕР ПРОСТАЯ ВЕРСИЯ
    • Только Supabase (без сторонних сервисов)
    • Кнопка "Создать ключ" в 1 клик
    • Auto Farm с платформой
    • God Mode
    • Fly (ПК + телефон)
    • Anti-AFK
    
    НАСТРОЙКА: Замените 2 строки в CONFIG!
]]

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local UserInputService = game:GetService("UserInputService")
local Workspace = game:GetService("Workspace")

-- ============================================
-- КОНФИГУРАЦИЯ (ЗАМЕНИТЕ ТОЛЬКО ЭТО!)
-- ============================================
local CONFIG = {
    -- Supabase (ОБЯЗАТЕЛЬНО ЗАМЕНИТЬ!)
    Supabase_URL = "https://wfnyprdzwrxeqgvtopqi.supabase.co",  -- Ваш Project URL
    Supabase_Key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3anN5d2xtdXp4bW5qanpveGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4MDcwOTEsImV4cCI6MjA5OTM4MzA5MX0.bKTXiAXxNWd_MWlPf9q0mPqL1yJQYuBgX-ylwD-Dmok",  -- Ваш anon public key
    
    -- Пароль для создания ключей
    AdminPassword = "REDKA"  -- Смените на свой!
}

-- ============================================
-- SQL ДЛЯ SUPABASE (выполнить 1 раз в SQL Editor):
-- ============================================
--[[
CREATE TABLE keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    hwid TEXT DEFAULT 'not_set',
    user_id BIGINT,
    username TEXT,
    expiry TEXT NOT NULL,
    created_at TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true
);

ALTER TABLE keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all" ON keys
    FOR ALL USING (true) WITH CHECK (true);
]]

-- ============================================
-- ПОЛУЧЕНИЕ HWID
-- ============================================
local function GetHWID()
    local success, hwid = pcall(function()
        return game:GetService("RbxAnalyticsService"):GetClientId()
    end)
    if not success then
        hwid = tostring(LocalPlayer.UserId) .. "-" .. tostring(math.random(1000, 9999))
    end
    return hwid
end

local HWID = GetHWID()
print("🔑 HWID:", HWID)

-- ============================================
-- ФУНКЦИИ SUPABASE
-- ============================================

-- Проверка ключа
local function CheckKey(key)
    print("🔍 Проверка ключа:", key)
    
    local url = CONFIG.Supabase_URL .. "/rest/v1/keys?key=eq." .. key .. "&is_active=eq.true&limit=1"
    
    local success, response = pcall(function()
        return HttpService:GetAsync(url, false, {
            ["apikey"] = CONFIG.Supabase_Key,
            ["Authorization"] = "Bearer " .. CONFIG.Supabase_Key
        })
    end)
    
    if not success then
        return false, "Ошибка соединения!"
    end
    
    local data = HttpService:JSONDecode(response)
    
    if #data == 0 then
        return false, "Неверный ключ!"
    end
    
    local keyData = data[1]
    local expiry = tonumber(keyData.expiry)
    
    -- Проверка срока
    if expiry and expiry < os.time() then
        DeactivateKey(keyData.id)
        return false, "Срок ключа истёк!"
    end
    
    -- Проверка HWID
    if keyData.hwid ~= "not_set" and keyData.hwid ~= HWID then
        return false, "Ключ уже используется!"
    end
    
    -- Привязка HWID
    if keyData.hwid == "not_set" then
        BindHWID(keyData.id)
    end
    
    print("✅ Ключ верный!")
    return true, "Ключ активирован!"
end

-- Привязка HWID
local function BindHWID(id)
    local url = CONFIG.Supabase_URL .. "/rest/v1/keys?id=eq." .. id
    
    pcall(function()
        HttpService:RequestAsync({
            Url = url,
            Method = "PATCH",
            Headers = {
                ["apikey"] = CONFIG.Supabase_Key,
                ["Authorization"] = "Bearer " .. CONFIG.Supabase_Key,
                ["Content-Type"] = "application/json",
                ["Prefer"] = "return=minimal"
            },
            Body = HttpService:JSONEncode({
                hwid = HWID,
                username = LocalPlayer.Name,
                user_id = LocalPlayer.UserId
            })
        })
    end)
end

-- Деактивация ключа
local function DeactivateKey(id)
    local url = CONFIG.Supabase_URL .. "/rest/v1/keys?id=eq." .. id
    
    pcall(function()
        HttpService:RequestAsync({
            Url = url,
            Method = "PATCH",
            Headers = {
                ["apikey"] = CONFIG.Supabase_Key,
                ["Authorization"] = "Bearer " .. CONFIG.Supabase_Key,
                ["Content-Type"] = "application/json",
                ["Prefer"] = "return=minimal"
            },
            Body = HttpService:JSONEncode({is_active = false})
        })
    end)
end

-- Генерация ключа
local function GenerateKey(duration_hours)
    -- Создаём случайный ключ
    local chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    local key = ""
    for i = 1, 4 do
        for j = 1, 4 do
            key = key .. chars:sub(math.random(1, #chars), math.random(1, #chars))
        end
        if i < 4 then key = key .. "-" end
    end
    
    -- Сохраняем в Supabase
    local url = CONFIG.Supabase_URL .. "/rest/v1/keys"
    local data = {
        key = key,
        hwid = "not_set",
        user_id = nil,
        username = nil,
        expiry = tostring(os.time() + (duration_hours * 3600)),
        created_at = tostring(os.time()),
        is_active = true
    }
    
    local success = pcall(function()
        HttpService:PostAsync(
            url,
            HttpService:JSONEncode(data),
            Enum.HttpContentType.ApplicationJson,
            false,
            {
                ["apikey"] = CONFIG.Supabase_Key,
                ["Authorization"] = "Bearer " .. CONFIG.Supabase_Key,
                ["Content-Type"] = "application/json",
                ["Prefer"] = "return=minimal"
            }
        )
    end)
    
    if success then
        print("✅ Ключ создан:", key)
        return key
    end
    
    return nil
end

-- Проверка сохраненного ключа (авто-вход)
local function CheckSavedKey()
    local url = CONFIG.Supabase_URL .. "/rest/v1/keys?hwid=eq." .. HWID .. "&is_active=eq.true&order=created_at.desc&limit=1"
    
    local success, response = pcall(function()
        return HttpService:GetAsync(url, false, {
            ["apikey"] = CONFIG.Supabase_Key,
            ["Authorization"] = "Bearer " .. CONFIG.Supabase_Key
        })
    end)
    
    if success then
        local data = HttpService:JSONDecode(response)
        if #data > 0 then
            local keyData = data[1]
            local expiry = tonumber(keyData.expiry)
            
            if expiry and expiry > os.time() then
                return true, keyData.key
            else
                DeactivateKey(keyData.id)
            end
        end
    end
    
    return false, nil
end

-- ============================================
-- ПЕРЕМЕННЫЕ ФУНКЦИЙ
-- ============================================
local Features = {
    AutoFarm = false,
    GodMode = false,
    FlyEnabled = false,
    AntiAFK = false,
    FarmSpeed = 1,
    FlySpeed = 50,
    Platform = nil,
    KeyValid = false
}

-- ============================================
-- ФУНКЦИИ СКРИПТА
-- ============================================

-- Платформа для фарма
local function CreatePlatform()
    if Features.Platform then
        Features.Platform:Destroy()
    end
    
    local character = LocalPlayer.Character
    if not character then return end
    
    local rootPart = character:FindFirstChild("HumanoidRootPart")
    if not rootPart then return end
    
    local platform = Instance.new("Part")
    platform.Name = "FarmPlatform"
    platform.Size = Vector3.new(15, 1, 15)
    platform.Anchored = true
    platform.CanCollide = true
    platform.Transparency = 0.3
    platform.BrickColor = BrickColor.new("Bright blue")
    platform.Material = Enum.Material.Neon
    platform.Parent = Workspace
    
    Features.Platform = platform
    
    spawn(function()
        while Features.AutoFarm and Features.Platform do
            wait()
            pcall(function()
                if LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart") and platform then
                    platform.CFrame = CFrame.new(LocalPlayer.Character.HumanoidRootPart.Position) * CFrame.new(0, -3.5, 0)
                end
            end)
        end
        if platform then
            platform:Destroy()
            Features.Platform = nil
        end
    end)
end

-- Авто-фарм
local function AutoFarm()
    CreatePlatform()
    
    spawn(function()
        while Features.AutoFarm do
            wait(0.1 / Features.FarmSpeed)
            pcall(function()
                local character = LocalPlayer.Character
                if not character then return end
                
                local rootPart = character:FindFirstChild("HumanoidRootPart")
                if not rootPart then return end
                
                for _, obj in ipairs(Workspace:GetDescendants()) do
                    if not Features.AutoFarm then break end
                    
                    if obj:IsA("BasePart") and obj:IsDescendantOf(Workspace) then
                        local name = obj.Name:lower()
                        if name:find("gold") or name:find("coin") or name:find("money") or name:find("chest") or name:find("block") then
                            if (obj.Position - rootPart.Position).Magnitude < 100 then
                                rootPart.CFrame = obj.CFrame * CFrame.new(0, 2, 0)
                                wait(0.05)
                                firetouchinterest(rootPart, obj, 0)
                                firetouchinterest(rootPart, obj, 1)
                            end
                        end
                    end
                end
            end)
        end
        
        if Features.Platform then
            Features.Platform:Destroy()
            Features.Platform = nil
        end
    end)
end

-- God Mode
local function GodMode()
    spawn(function()
        while Features.GodMode do
            wait()
            pcall(function()
                local character = LocalPlayer.Character
                if not character then return end
                
                local humanoid = character:FindFirstChild("Humanoid")
                if humanoid then
                    humanoid.Health = humanoid.MaxHealth
                end
                
                for _, part in ipairs(character:GetDescendants()) do
                    if part:IsA("BasePart") then
                        part.CanCollide = false
                    end
                end
            end)
        end
    end)
end

-- Fly (ПК + телефон)
local function Fly()
    local character = LocalPlayer.Character
    if not character then return end
    
    local humanoid = character:FindFirstChild("Humanoid")
    local rootPart = character:FindFirstChild("HumanoidRootPart")
    
    if not humanoid or not rootPart then return end
    
    local bodyGyro = Instance.new("BodyGyro")
    bodyGyro.CFrame = rootPart.CFrame
    bodyGyro.MaxTorque = Vector3.new(400000, 400000, 400000)
    bodyGyro.P = 30000
    bodyGyro.Parent = rootPart
    
    local bodyVelocity = Instance.new("BodyVelocity")
    bodyVelocity.Velocity = Vector3.new(0, 0, 0)
    bodyVelocity.MaxForce = Vector3.new(400000, 400000, 400000)
    bodyVelocity.P = 30000
    bodyVelocity.Parent = rootPart
    
    spawn(function()
        while Features.FlyEnabled do
            wait()
            if not LocalPlayer.Character or not rootPart or not rootPart.Parent then break end
            
            bodyGyro.CFrame = Workspace.CurrentCamera.CFrame
            
            local velocity = Vector3.new(0, 0, 0)
            
            if UserInputService:IsKeyDown(Enum.KeyCode.W) then
                velocity = velocity + Workspace.CurrentCamera.CFrame.LookVector * Features.FlySpeed
            end
            if UserInputService:IsKeyDown(Enum.KeyCode.S) then
                velocity = velocity - Workspace.CurrentCamera.CFrame.LookVector * Features.FlySpeed
            end
            if UserInputService:IsKeyDown(Enum.KeyCode.A) then
                velocity = velocity - Workspace.CurrentCamera.CFrame.RightVector * Features.FlySpeed
            end
            if UserInputService:IsKeyDown(Enum.KeyCode.D) then
                velocity = velocity + Workspace.CurrentCamera.CFrame.RightVector * Features.FlySpeed
            end
            if UserInputService:IsKeyDown(Enum.KeyCode.Space) then
                velocity = velocity + Vector3.new(0, Features.FlySpeed, 0)
            end
            if UserInputService:IsKeyDown(Enum.KeyCode.LeftShift) then
                velocity = velocity - Vector3.new(0, Features.FlySpeed, 0)
            end
            
            bodyVelocity.Velocity = velocity
        end
        
        bodyGyro:Destroy()
        bodyVelocity:Destroy()
    end)
    
    -- Мобильные кнопки
    if UserInputService.TouchEnabled then
        CreateMobileButtons(rootPart, bodyVelocity)
    end
end

-- Мобильные кнопки для полёта
local function CreateMobileButtons(rootPart, bodyVelocity)
    local MobileGui = Instance.new("ScreenGui")
    MobileGui.Name = "MobileFly"
    MobileGui.Parent = LocalPlayer:WaitForChild("PlayerGui")
    
    local buttons = {
        {Text = "▲", Pos = UDim2.new(0.5, -30, 0.7, -80), Dir = "Forward"},
        {Text = "▼", Pos = UDim2.new(0.5, -30, 0.7, 50), Dir = "Backward"},
        {Text = "◀", Pos = UDim2.new(0.5, -95, 0.7, -15), Dir = "Left"},
        {Text = "▶", Pos = UDim2.new(0.5, 35, 0.7, -15), Dir = "Right"},
        {Text = "⇧", Pos = UDim2.new(0.8, -35, 0.75, -35), Dir = "Up"},
        {Text = "⇩", Pos = UDim2.new(0.8, -35, 0.85, -35), Dir = "Down"},
    }
    
    local activeButtons = {}
    
    for _, btnData in ipairs(buttons) do
        local btn = Instance.new("TextButton")
        btn.Size = UDim2.new(0, 60, 0, 60)
        btn.Position = btnData.Pos
        btn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        btn.BackgroundTransparency = 0.7
        btn.Text = btnData.Text
        btn.TextColor3 = Color3.fromRGB(0, 0, 0)
        btn.TextSize = 30
        btn.Font = Enum.Font.GothamBold
        btn.BorderSizePixel = 0
        btn.Parent = MobileGui
        
        btn.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.Touch then
                activeButtons[btnData.Dir] = true
            end
        end)
        
        btn.InputEnded:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.Touch then
                activeButtons[btnData.Dir] = false
            end
        end)
    end
    
    spawn(function()
        while Features.FlyEnabled do
            wait()
            if not rootPart or not rootPart.Parent then break end
            
            local velocity = Vector3.new(0, 0, 0)
            
            if activeButtons["Forward"] then
                velocity = velocity + Workspace.CurrentCamera.CFrame.LookVector * Features.FlySpeed
            end
            if activeButtons["Backward"] then
                velocity = velocity - Workspace.CurrentCamera.CFrame.LookVector * Features.FlySpeed
            end
            if activeButtons["Left"] then
                velocity = velocity - Workspace.CurrentCamera.CFrame.RightVector * Features.FlySpeed
            end
            if activeButtons["Right"] then
                velocity = velocity + Workspace.CurrentCamera.CFrame.RightVector * Features.FlySpeed
            end
            if activeButtons["Up"] then
                velocity = velocity + Vector3.new(0, Features.FlySpeed, 0)
            end
            if activeButtons["Down"] then
                velocity = velocity - Vector3.new(0, Features.FlySpeed, 0)
            end
            
            bodyVelocity.Velocity = velocity
        end
        
        MobileGui:Destroy()
    end)
end

-- Анти-АФК
local function AntiAFKSystem()
    spawn(function()
        while Features.AntiAFK do
            wait(5)
            
            pcall(function()
                local character = LocalPlayer.Character
                if not character then return end
                
                local rootPart = character:FindFirstChild("HumanoidRootPart")
                if rootPart then
                    local originalPos = rootPart.Position
                    local randomDir = Vector3.new(
                        math.random(-100, 100) / 1000,
                        0,
                        math.random(-100, 100) / 1000
                    )
                    
                    rootPart.CFrame = rootPart.CFrame * CFrame.new(randomDir)
                    wait(0.1)
                    rootPart.CFrame = CFrame.new(originalPos)
                end
            end)
        end
    end)
end

-- ============================================
-- АДМИН-ПАНЕЛЬ (СОЗДАНИЕ КЛЮЧЕЙ)
-- ============================================
local function CreateAdminPanel()
    local AdminGui = Instance.new("ScreenGui")
    AdminGui.Name = "AdminPanel"
    AdminGui.Parent = game:GetService("CoreGui")
    
    local Frame = Instance.new("Frame")
    Frame.Size = UDim2.new(0, 300, 0, 280)
    Frame.Position = UDim2.new(0.5, -150, 0.5, -140)
    Frame.BackgroundColor3 = Color3.fromRGB(30, 30, 40)
    Frame.BorderSizePixel = 0
    Frame.Active = true
    Frame.Draggable = true
    Frame.Parent = AdminGui
    
    -- Заголовок
    local Title = Instance.new("TextLabel")
    Title.Size = UDim2.new(1, 0, 0, 35)
    Title.BackgroundColor3 = Color3.fromRGB(40, 40, 60)
    Title.Text = "🔑 Создание ключа"
    Title.TextColor3 = Color3.fromRGB(255, 215, 0)
    Title.Font = Enum.Font.GothamBold
    Title.TextSize = 16
    Title.BorderSizePixel = 0
    Title.Parent = Frame
    
    -- Пароль
    local PassInput = Instance.new("TextBox")
    PassInput.Size = UDim2.new(1, -20, 0, 30)
    PassInput.Position = UDim2.new(0, 10, 0, 45)
    PassInput.BackgroundColor3 = Color3.fromRGB(50, 50, 70)
    PassInput.TextColor3 = Color3.fromRGB(255, 255, 255)
    PassInput.PlaceholderText = "🔐 Пароль..."
    PassInput.Font = Enum.Font.Gotham
    PassInput.TextSize = 13
    PassInput.BorderSizePixel = 0
    PassInput.Parent = Frame
    
    -- Длительность
    local DurationInput = Instance.new("TextBox")
    DurationInput.Size = UDim2.new(1, -20, 0, 30)
    DurationInput.Position = UDim2.new(0, 10, 0, 85)
    DurationInput.BackgroundColor3 = Color3.fromRGB(50, 50, 70)
    DurationInput.TextColor3 = Color3.fromRGB(255, 255, 255)
    DurationInput.PlaceholderText = "⏱️ Часов (24 = 1 день)..."
    DurationInput.Text = "24"
    DurationInput.Font = Enum.Font.Gotham
    DurationInput.TextSize = 13
    DurationInput.BorderSizePixel = 0
    DurationInput.Parent = Frame
    
    -- Кнопка создать
    local CreateButton = Instance.new("TextButton")
    CreateButton.Size = UDim2.new(1, -20, 0, 40)
    CreateButton.Position = UDim2.new(0, 10, 0, 125)
    CreateButton.BackgroundColor3 = Color3.fromRGB(0, 170, 0)
    CreateButton.Text = "🎲 СОЗДАТЬ КЛЮЧ"
    CreateButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    CreateButton.Font = Enum.Font.GothamBold
    CreateButton.TextSize = 16
    CreateButton.BorderSizePixel = 0
    CreateButton.Parent = Frame
    
    -- Поле с ключом
    local KeyDisplay = Instance.new("TextBox")
    KeyDisplay.Size = UDim2.new(1, -20, 0, 35)
    KeyDisplay.Position = UDim2.new(0, 10, 0, 175)
    KeyDisplay.BackgroundColor3 = Color3.fromRGB(50, 50, 70)
    KeyDisplay.TextColor3 = Color3.fromRGB(0, 255, 0)
    KeyDisplay.Text = "Нажмите СОЗДАТЬ..."
    KeyDisplay.Font = Enum.Font.GothamBold
    KeyDisplay.TextSize = 14
    KeyDisplay.BorderSizePixel = 0
    KeyDisplay.ClearTextOnFocus = false
    KeyDisplay.Parent = Frame
    
    -- Статус
    local Status = Instance.new("TextLabel")
    Status.Size = UDim2.new(1, -20, 0, 25)
    Status.Position = UDim2.new(0, 10, 0, 220)
    Status.BackgroundTransparency = 1
    Status.Text = ""
    Status.TextColor3 = Color3.fromRGB(255, 255, 255)
    Status.Font = Enum.Font.Gotham
    Status.TextSize = 12
    Status.Parent = Frame
    
    -- Кнопка закрыть
    local CloseBtn = Instance.new("TextButton")
    CloseBtn.Size = UDim2.new(1, -20, 0, 30)
    CloseBtn.Position = UDim2.new(0, 10, 0, 250)
    CloseBtn.BackgroundColor3 = Color3.fromRGB(255, 50, 50)
    CloseBtn.Text = "✕ Закрыть"
    CloseBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
    CloseBtn.Font = Enum.Font.GothamBold
    CloseBtn.TextSize = 13
    CloseBtn.BorderSizePixel = 0
    CloseBtn.Parent = Frame
    
    -- Копирование при нажатии на ключ
    KeyDisplay.Focused:Connect(function()
        KeyDisplay:ReleaseFocus()
        if KeyDisplay.Text ~= "Нажмите СОЗДАТЬ..." then
            pcall(function()
                setclipboard(KeyDisplay.Text)
                Status.Text = "✅ Ключ скопирован!"
                Status.TextColor3 = Color3.fromRGB(0, 255, 0)
            end)
        end
    end)
    
    -- Создание ключа
    CreateButton.MouseButton1Click:Connect(function()
        if PassInput.Text ~= CONFIG.AdminPassword then
            Status.Text = "❌ Неверный пароль!"
            Status.TextColor3 = Color3.fromRGB(255, 100, 100)
            return
        end
        
        local duration = tonumber(DurationInput.Text) or 24
        if duration <= 0 or duration > 8760 then
            Status.Text = "❌ От 1 до 8760 часов!"
            Status.TextColor3 = Color3.fromRGB(255, 100, 100)
            return
        end
        
        Status.Text = "⏳ Создание ключа..."
        Status.TextColor3 = Color3.fromRGB(255, 200, 0)
        
        local key = GenerateKey(duration)
        
        if key then
            KeyDisplay.Text = key
            Status.Text = "✅ Готово! Нажми на ключ чтобы скопировать"
            Status.TextColor3 = Color3.fromRGB(0, 255, 0)
        else
            Status.Text = "❌ Ошибка! Проверь Supabase"
            Status.TextColor3 = Color3.fromRGB(255, 100, 100)
        end
    end)
    
    CloseBtn.MouseButton1Click:Connect(function()
        AdminGui:Destroy()
    end)
end

-- ============================================
-- ГЛАВНЫЙ GUI
-- ============================================
local function CreateMainGUI()
    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = "BABFT_Hack"
    ScreenGui.Parent = game:GetService("CoreGui")
    ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    
    -- Main Frame
    local MainFrame = Instance.new("Frame")
    MainFrame.Size = UDim2.new(0, 550, 0, 420)
    MainFrame.Position = UDim2.new(0.5, -275, 0.5, -210)
    MainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 35)
    MainFrame.BorderSizePixel = 0
    MainFrame.Active = true
    MainFrame.Draggable = true
    MainFrame.Parent = ScreenGui
    
    -- Title Bar
    local TitleBar = Instance.new("Frame")
    TitleBar.Size = UDim2.new(1, 0, 0, 35)
    TitleBar.BackgroundColor3 = Color3.fromRGB(35, 35, 50)
    TitleBar.BorderSizePixel = 0
    TitleBar.Parent = MainFrame
    
    local Title = Instance.new("TextLabel")
    Title.Size = UDim2.new(1, -50, 1, 0)
    Title.Position = UDim2.new(0, 15, 0, 0)
    Title.BackgroundTransparency = 1
    Title.Text = "🌟 BABFT HACK v2.0"
    Title.TextColor3 = Color3.fromRGB(255, 215, 0)
    Title.TextSize = 16
    Title.Font = Enum.Font.GothamBold
    Title.TextXAlignment = Enum.TextXAlignment.Left
    Title.Parent = TitleBar
    
    local CloseButton = Instance.new("TextButton")
    CloseButton.Size = UDim2.new(0, 30, 0, 30)
    CloseButton.Position = UDim2.new(1, -35, 0, 2)
    CloseButton.BackgroundColor3 = Color3.fromRGB(255, 50, 50)
    CloseButton.Text = "✕"
    CloseButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    CloseButton.TextSize = 16
    CloseButton.Font = Enum.Font.GothamBold
    CloseButton.BorderSizePixel = 0
    CloseButton.Parent = TitleBar
    
    -- Tab Buttons
    local TabFrame = Instance.new("Frame")
    TabFrame.Size = UDim2.new(0, 130, 1, -35)
    TabFrame.Position = UDim2.new(0, 0, 0, 35)
    TabFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 45)
    TabFrame.BorderSizePixel = 0
    TabFrame.Parent = MainFrame
    
    local Tabs = {}
    local TabButtons = {}
    local TabNames = {"🔑 Ключ", "⚔️ Фарм", "🛡️ Год", "✈️ Полёт", "🤖 АнтиАФК"}
    
    for i, name in ipairs(TabNames) do
        local TabButton = Instance.new("TextButton")
        TabButton.Size = UDim2.new(1, -10, 0, 32)
        TabButton.Position = UDim2.new(0, 5, 0, 8 + (i-1)*37)
        TabButton.BackgroundColor3 = (i == 1) and Color3.fromRGB(60, 60, 100) or Color3.fromRGB(45, 45, 70)
        TabButton.Text = name
        TabButton.TextColor3 = Color3.fromRGB(255, 255, 255)
        TabButton.TextSize = 13
        TabButton.Font = Enum.Font.Gotham
        TabButton.BorderSizePixel = 0
        TabButton.Parent = TabFrame
        TabButtons[i] = TabButton
        
        local Page = Instance.new("Frame")
        Page.Size = UDim2.new(1, -140, 1, -45)
        Page.Position = UDim2.new(0, 135, 0, 40)
        Page.BackgroundTransparency = 1
        Page.Visible = (i == 1)
        Page.Parent = MainFrame
        Tabs[i] = Page
        
        TabButton.MouseButton1Click:Connect(function()
            for j, p in ipairs(Tabs) do
                p.Visible = (j == i)
            end
            for j, btn in ipairs(TabButtons) do
                btn.BackgroundColor3 = (j == i) and Color3.fromRGB(60, 60, 100) or Color3.fromRGB(45, 45, 70)
            end
        end)
    end
    
    -- ========== KEY PAGE ==========
    local KeyPage = Tabs[1]
    
    local KeyInput = Instance.new("TextBox")
    KeyInput.Size = UDim2.new(1, -20, 0, 35)
    KeyInput.Position = UDim2.new(0, 10, 0, 20)
    KeyInput.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    KeyInput.TextColor3 = Color3.fromRGB(255, 255, 255)
    KeyInput.PlaceholderText = "Введите ключ..."
    KeyInput.PlaceholderColor3 = Color3.fromRGB(150, 150, 150)
    KeyInput.Font = Enum.Font.Gotham
    KeyInput.TextSize = 14
    KeyInput.BorderSizePixel = 0
    KeyInput.Parent = KeyPage
    
    local KeyStatus = Instance.new("TextLabel")
    KeyStatus.Size = UDim2.new(1, -20, 0, 45)
    KeyStatus.Position = UDim2.new(0, 10, 0, 65)
    KeyStatus.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    KeyStatus.Text = "Статус: Ожидание ключа..."
    KeyStatus.TextColor3 = Color3.fromRGB(255, 200, 0)
    KeyStatus.Font = Enum.Font.Gotham
    KeyStatus.TextSize = 12
    KeyStatus.TextXAlignment = Enum.TextXAlignment.Center
    KeyStatus.BorderSizePixel = 0
    KeyStatus.Parent = KeyPage
    
    local ActivateButton = Instance.new("TextButton")
    ActivateButton.Size = UDim2.new(0, 160, 0, 38)
    ActivateButton.Position = UDim2.new(0.5, -80, 0, 120)
    ActivateButton.BackgroundColor3 = Color3.fromRGB(0, 180, 0)
    ActivateButton.Text = "🔓 Активировать"
    ActivateButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    ActivateButton.Font = Enum.Font.GothamBold
    ActivateButton.TextSize = 15
    ActivateButton.BorderSizePixel = 0
    ActivateButton.Parent = KeyPage
    
    local HWIDLabel = Instance.new("TextLabel")
    HWIDLabel.Size = UDim2.new(1, -20, 0, 25)
    HWIDLabel.Position = UDim2.new(0, 10, 0, 175)
    HWIDLabel.BackgroundColor3 = Color3.fromRGB(35, 35, 55)
    HWIDLabel.Text = "HWID: " .. HWID
    HWIDLabel.TextColor3 = Color3.fromRGB(180, 180, 200)
    HWIDLabel.Font = Enum.Font.Gotham
    HWIDLabel.TextSize = 10
    HWIDLabel.TextXAlignment = Enum.TextXAlignment.Center
    HWIDLabel.BorderSizePixel = 0
    HWIDLabel.Parent = KeyPage
    
    -- ========== FARM PAGE ==========
    local FarmPage = Tabs[2]
    
    local FarmToggle = Instance.new("TextButton")
    FarmToggle.Size = UDim2.new(1, -20, 0, 42)
    FarmToggle.Position = UDim2.new(0, 10, 0, 20)
    FarmToggle.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
    FarmToggle.Text = "⚔️ Auto Farm: OFF"
    FarmToggle.TextColor3 = Color3.fromRGB(255, 255, 255)
    FarmToggle.Font = Enum.Font.GothamBold
    FarmToggle.TextSize = 15
    FarmToggle.BorderSizePixel = 0
    FarmToggle.Parent = FarmPage
    
    local PlatformInfo = Instance.new("TextLabel")
    PlatformInfo.Size = UDim2.new(1, -20, 0, 35)
    PlatformInfo.Position = UDim2.new(0, 10, 0, 72)
    PlatformInfo.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    PlatformInfo.Text = "🔷 Платформа под игроком"
    PlatformInfo.TextColor3 = Color3.fromRGB(180, 200, 255)
    PlatformInfo.Font = Enum.Font.Gotham
    PlatformInfo.TextSize = 11
    PlatformInfo.TextXAlignment = Enum.TextXAlignment.Center
    PlatformInfo.BorderSizePixel = 0
    PlatformInfo.Parent = FarmPage
    
    local FarmSpeedLabel = Instance.new("TextLabel")
    FarmSpeedLabel.Size = UDim2.new(1, -20, 0, 22)
    FarmSpeedLabel.Position = UDim2.new(0, 10, 0, 120)
    FarmSpeedLabel.BackgroundTransparency = 1
    FarmSpeedLabel.Text = "Скорость: 1x"
    FarmSpeedLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
    FarmSpeedLabel.Font = Enum.Font.Gotham
    FarmSpeedLabel.TextSize = 12
    FarmSpeedLabel.TextXAlignment = Enum.TextXAlignment.Left
    FarmSpeedLabel.Parent = FarmPage
    
    local SpeedUpButton = Instance.new("TextButton")
    SpeedUpButton.Size = UDim2.new(0, 70, 0, 28)
    SpeedUpButton.Position = UDim2.new(0, 10, 0, 150)
    SpeedUpButton.BackgroundColor3 = Color3.fromRGB(0, 120, 255)
    SpeedUpButton.Text = "➕ +"
    SpeedUpButton.Font = Enum.Font.Gotham
    SpeedUpButton.TextSize = 12
    SpeedUpButton.BorderSizePixel = 0
    SpeedUpButton.Parent = FarmPage
    
    local SpeedDownButton = Instance.new("TextButton")
    SpeedDownButton.Size = UDim2.new(0, 70, 0, 28)
    SpeedDownButton.Position = UDim2.new(0, 90, 0, 150)
    SpeedDownButton.BackgroundColor3 = Color3.fromRGB(255, 100, 0)
    SpeedDownButton.Text = "➖ -"
    SpeedDownButton.Font = Enum.Font.Gotham
    SpeedDownButton.TextSize = 12
    SpeedDownButton.BorderSizePixel = 0
    SpeedDownButton.Parent = FarmPage
    
    -- ========== GOD PAGE ==========
    local GodPage = Tabs[3]
    
    local GodToggle = Instance.new("TextButton")
    GodToggle.Size = UDim2.new(1, -20, 0, 42)
    GodToggle.Position = UDim2.new(0, 10, 0, 20)
    GodToggle.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
    GodToggle.Text = "🛡️ God Mode: OFF"
    GodToggle.TextColor3 = Color3.fromRGB(255, 255, 255)
    GodToggle.Font = Enum.Font.GothamBold
    GodToggle.TextSize = 15
    GodToggle.BorderSizePixel = 0
    GodToggle.Parent = GodPage
    
    local GodInfo = Instance.new("TextLabel")
    GodInfo.Size = UDim2.new(1, -20, 0, 70)
    GodInfo.Position = UDim2.new(0, 10, 0, 80)
    GodInfo.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    GodInfo.Text = "🛡️ Бесконечное здоровье\n👻 Нет коллизии\n💪 Неуязвимость"
    GodInfo.TextColor3 = Color3.fromRGB(255, 255, 255)
    GodInfo.Font = Enum.Font.Gotham
    GodInfo.TextSize = 11
    GodInfo.TextXAlignment = Enum.TextXAlignment.Left
    GodInfo.BorderSizePixel = 0
    GodInfo.Parent = GodPage
    
    -- ========== FLY PAGE ==========
    local FlyPage = Tabs[4]
    
    local FlyToggle = Instance.new("TextButton")
    FlyToggle.Size = UDim2.new(1, -20, 0, 42)
    FlyToggle.Position = UDim2.new(0, 10, 0, 20)
    FlyToggle.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
    FlyToggle.Text = "✈️ Fly: OFF"
    FlyToggle.TextColor3 = Color3.fromRGB(255, 255, 255)
    FlyToggle.Font = Enum.Font.GothamBold
    FlyToggle.TextSize = 15
    FlyToggle.BorderSizePixel = 0
    FlyToggle.Parent = FlyPage
    
    local FlySpeedLabel = Instance.new("TextLabel")
    FlySpeedLabel.Size = UDim2.new(1, -20, 0, 22)
    FlySpeedLabel.Position = UDim2.new(0, 10, 0, 75)
    FlySpeedLabel.BackgroundTransparency = 1
    FlySpeedLabel.Text = "Скорость: 50"
    FlySpeedLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
    FlySpeedLabel.Font = Enum.Font.Gotham
    FlySpeedLabel.TextSize = 12
    FlySpeedLabel.TextXAlignment = Enum.TextXAlignment.Left
    FlySpeedLabel.Parent = FlyPage
    
    local FlySpeedUp = Instance.new("TextButton")
    FlySpeedUp.Size = UDim2.new(0, 70, 0, 28)
    FlySpeedUp.Position = UDim2.new(0, 10, 0, 105)
    FlySpeedUp.BackgroundColor3 = Color3.fromRGB(0, 120, 255)
    FlySpeedUp.Text = "➕ +"
    FlySpeedUp.Font = Enum.Font.Gotham
    FlySpeedUp.TextSize = 12
    FlySpeedUp.BorderSizePixel = 0
    FlySpeedUp.Parent = FlyPage
    
    local FlySpeedDown = Instance.new("TextButton")
    FlySpeedDown.Size = UDim2.new(0, 70, 0, 28)
    FlySpeedDown.Position = UDim2.new(0, 90, 0, 105)
    FlySpeedDown.BackgroundColor3 = Color3.fromRGB(255, 100, 0)
    FlySpeedDown.Text = "➖ -"
    FlySpeedDown.Font = Enum.Font.Gotham
    FlySpeedDown.TextSize = 12
    FlySpeedDown.BorderSizePixel = 0
    FlySpeedDown.Parent = FlyPage
    
    local FlyInfo = Instance.new("TextLabel")
    FlyInfo.Size = UDim2.new(1, -20, 0, 50)
    FlyInfo.Position = UDim2.new(0, 10, 0, 145)
    FlyInfo.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    FlyInfo.Text = "🎮 ПК: WASD + Space/Shift\n📱 Телефон: кнопки на экране"
    FlyInfo.TextColor3 = Color3.fromRGB(255, 255, 255)
    FlyInfo.Font = Enum.Font.Gotham
    FlyInfo.TextSize = 11
    FlyInfo.TextXAlignment = Enum.TextXAlignment.Left
    FlyInfo.BorderSizePixel = 0
    FlyInfo.Parent = FlyPage
    
    -- ========== ANTI-AFK PAGE ==========
    local AntiAFKPage = Tabs[5]
    
    local AntiAFKToggle = Instance.new("TextButton")
    AntiAFKToggle.Size = UDim2.new(1, -20, 0, 42)
    AntiAFKToggle.Position = UDim2.new(0, 10, 0, 20)
    AntiAFKToggle.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
    AntiAFKToggle.Text = "🤖 Anti-AFK: OFF"
    AntiAFKToggle.TextColor3 = Color3.fromRGB(255, 255, 255)
    AntiAFKToggle.Font = Enum.Font.GothamBold
    AntiAFKToggle.TextSize = 15
    AntiAFKToggle.BorderSizePixel = 0
    AntiAFKToggle.Parent = AntiAFKPage
    
    local AntiAFKInfo = Instance.new("TextLabel")
    AntiAFKInfo.Size = UDim2.new(1, -20, 0, 90)
    AntiAFKInfo.Position = UDim2.new(0, 10, 0, 80)
    AntiAFKInfo.BackgroundColor3 = Color3.fromRGB(45, 45, 70)
    AntiAFKInfo.Text = "🤖 Анти-АФК:\n\n• Шаг каждые 5 сек\n• Случайное направление\n• Защита от кика"
    AntiAFKInfo.TextColor3 = Color3.fromRGB(200, 255, 200)
    AntiAFKInfo.Font = Enum.Font.Gotham
    AntiAFKInfo.TextSize = 11
    AntiAFKInfo.TextXAlignment = Enum.TextXAlignment.Left
    AntiAFKInfo.BorderSizePixel = 0
    AntiAFKInfo.Parent = AntiAFKPage
    
    -- ========== BUTTON HANDLERS ==========
    
    CloseButton.MouseButton1Click:Connect(function()
        Features.AutoFarm = false
        Features.GodMode = false
        Features.FlyEnabled = false
        Features.AntiAFK = false
        
        if Features.Platform then
            Features.Platform:Destroy()
        end
        
        ScreenGui:Destroy()
    end)
    
    ActivateButton.MouseButton1Click:Connect(function()
        local key = KeyInput.Text
        if key == "" then
            KeyStatus.Text = "❌ Введите ключ!"
            KeyStatus.TextColor3 = Color3.fromRGB(255, 100, 100)
            return
        end
        
        KeyStatus.Text = "⏳ Проверка..."
        KeyStatus.TextColor3 = Color3.fromRGB(255, 200, 0)
        
        local valid, message = CheckKey(key)
        
        if valid then
            Features.KeyValid = true
            KeyStatus.Text = message
            KeyStatus.TextColor3 = Color3.fromRGB(100, 255, 100)
            ActivateButton.Text = "✅ Готово"
            ActivateButton.BackgroundColor3 = Color3.fromRGB(0, 120, 0)
        else
            KeyStatus.Text = message
            KeyStatus.TextColor3 = Color3.fromRGB(255, 100, 100)
        end
    end)
    
    FarmToggle.MouseButton1Click:Connect(function()
        if not Features.KeyValid then return end
        
        Features.AutoFarm = not Features.AutoFarm
        FarmToggle.Text = "⚔️ Auto Farm: " .. (Features.AutoFarm and "ON" or "OFF")
        FarmToggle.BackgroundColor3 = Features.AutoFarm and Color3.fromRGB(0, 170, 0) or Color3.fromRGB(200, 50, 50)
        
        if Features.AutoFarm then AutoFarm() end
    end)
    
    SpeedUpButton.MouseButton1Click:Connect(function()
        if Features.FarmSpeed < 10 then
            Features.FarmSpeed = Features.FarmSpeed + 1
            FarmSpeedLabel.Text = "Скорость: " .. Features.FarmSpeed .. "x"
        end
    end)
    
    SpeedDownButton.MouseButton1Click:Connect(function()
        if Features.FarmSpeed > 1 then
            Features.FarmSpeed = Features.FarmSpeed - 1
            FarmSpeedLabel.Text = "Скорость: " .. Features.FarmSpeed .. "x"
        end
    end)
    
    GodToggle.MouseButton1Click:Connect(function()
        if not Features.KeyValid then return end
        
        Features.GodMode = not Features.GodMode
        GodToggle.Text = "🛡️ God Mode: " .. (Features.GodMode and "ON" or "OFF")
        GodToggle.BackgroundColor3 = Features.GodMode and Color3.fromRGB(0, 170, 0) or Color3.fromRGB(200, 50, 50)
        
        if Features.GodMode then GodMode() end
    end)
    
    FlyToggle.MouseButton1Click:Connect(function()
        if not Features.KeyValid then return end
        
        Features.FlyEnabled = not Features.FlyEnabled
        FlyToggle.Text = "✈️ Fly: " .. (Features.FlyEnabled and "ON" or "OFF")
        FlyToggle.BackgroundColor3 = Features.FlyEnabled and Color3.fromRGB(0, 170, 0) or Color3.fromRGB(200, 50, 50)
        
        if Features.FlyEnabled then Fly() end
    end)
    
    FlySpeedUp.MouseButton1Click:Connect(function()
        Features.FlySpeed = math.min(Features.FlySpeed + 10, 200)
        FlySpeedLabel.Text = "Скорость: " .. Features.FlySpeed
    end)
    
    FlySpeedDown.MouseButton1Click:Connect(function()
        Features.FlySpeed = math.max(Features.FlySpeed - 10, 10)
        FlySpeedLabel.Text = "Скорость: " .. Features.FlySpeed
    end)
    
    AntiAFKToggle.MouseButton1Click:Connect(function()
        if not Features.KeyValid then return end
        
        Features.AntiAFK = not Features.AntiAFK
        AntiAFKToggle.Text = "🤖 Anti-AFK: " .. (Features.AntiAFK and "ON" or "OFF")
        AntiAFKToggle.BackgroundColor3 = Features.AntiAFK and Color3.fromRGB(0, 170, 0) or Color3.fromRGB(200, 50, 50)
        
        if Features.AntiAFK then AntiAFKSystem() end
    end)
    
    -- Кнопка админ-панели
    local AdminBtn = Instance.new("TextButton")
    AdminBtn.Size = UDim2.new(0, 140, 0, 22)
    AdminBtn.Position = UDim2.new(1, -150, 0, 8)
    AdminBtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    AdminBtn.BackgroundTransparency = 0.5
    AdminBtn.Text = "🔑 СОЗДАТЬ КЛЮЧ"
    AdminBtn.TextColor3 = Color3.fromRGB(255, 215, 0)
    AdminBtn.Font = Enum.Font.GothamBold
    AdminBtn.TextSize = 10
    AdminBtn.BorderSizePixel = 0
    AdminBtn.Parent = ScreenGui
    
    AdminBtn.MouseButton1Click:Connect(function()
        CreateAdminPanel()
    end)
    
    -- Авто-вход
    spawn(function()
        local valid, savedKey = CheckSavedKey()
        if valid and savedKey then
            Features.KeyValid = true
            KeyStatus.Text = "✅ Авто-вход выполнен!"
            KeyStatus.TextColor3 = Color3.fromRGB(100, 255, 100)
            ActivateButton.Text = "✅ Готово"
            ActivateButton.BackgroundColor3 = Color3.fromRGB(0, 120, 0)
            KeyInput.Text = savedKey
        end
    end)
end

-- ============================================
-- ЗАПУСК
-- ============================================
print("🌟 BABFT HACK v2.0 загружен!")
print("🔑 HWID:", HWID)
print("💾 Supabase:", CONFIG.Supabase_URL ~= "https://wfnyprdzwrxeqgvtopqi.supabase.co" and "✅ Настроен" or "❌ Настройте URL!")

CreateMainGUI()
